var = {
    "name": "DAS Digitile Installation",
    "description": "DAS Digitile Installation",
    "summary": "DAS Digitile Installation",
    "version": "16.0.1.0.1",
    "author": "Das360",
    "depends": ["sale_management", "purchase", "point_of_sale", "stock",  "das_digitile",
                "das_template_settings", "das_delivery_system", "das_publicfunction", "das_user_notification",
                "das_car_driver_ok", "das_orders_trip",
                "das_zone_location", "das_images_attachment", "das_sale_order_product", "das_sign_u_module",
                "das_event_sale_order", "das_bill_of_material", "das_categorygroups", "das_career",
                "das_company_informations", "das_bi_website_faq",
                "das_sh_message", "das_customer_feedback", "das_delivery_fees",
                "contacts_maps", "das_disable_configure", "das_sale_order_kanban", "das_working_days",
                "das_pos_order_to_sale_order", "das_contact_us", "das_delivery_item", "das_delivery_time",
                "das_company_type_settings", "das_website_banners_faq", "das_website_banners_career",
                "das_website_banners_category", "das_website_banners_checkout", "das_website_banners_cart",
                "das_website_banners_deal",
                "das_company_logo_attachment", "das_partner_create_user",
                "das_retailer_orders", "das_first_order", "das_manager", "das_time_to_assign_to_driver",
                "das_time_to_assign_to_driver", "das_timeslot", "das_about_us", "das_about_us_mission",
                "das_about_us_vision", "das_about_us_value", "das_about_us_slider", "das_team",
                "das_main_page_banners1", "das_main_page_banners2", "das_main_page_banners3", "das_main_page_sections",
                "das_branches_api", "das_chef", "das_client_api", "das_drivers_api", "das_uninstall_trigger",
                "das_uninstall_trigger_pos"],

    'installable': True,
    'sequence': -100,
    'application': True,
    'auto_install': False,
    "license": 'AGPL-3',
    "website": "https://das-360.com",

}
