{
    "name": "DAS Digitile Installation Template 4",
    "description": "DAS Digitile Installation Template 4",
    "summary": "DAS Digitile Installation Template 4",
    "version": "16.0.1.0.1",
    "author": "Das360",
    "depends": ["sale_management",  "mrp", "das_digitile","das_template_settings","das_publicfunction","das_delivery_system","das_delivery_item","das_delivery_time","das_user_notification","das_car_driver_ok","das_orders_trip",
                "das_zone_location","das_images_attachment","das_sign_u_module",  "das_categorygroups", "das_company_informations",
                "das_sh_message","das_sale_order_product",
                "contacts_maps","das_disable_configure","das_sale_order_kanban","das_working_days", "das_contact_us","das_delivery_fees",
                "das_company_type_settings",
                "das_website_banners_category",
                "das_company_logo_attachment","das_partner_create_user","das_event_sale_order",
                "das_retailer_orders","das_first_order","das_manager","das_time_to_assign_to_driver",
                "das_time_to_assign_to_driver","das_timeslot","das_about_us",
                "das_about_us_mission","das_add_zone_to_partner","das_career","das_website_banners_career",
                "das_bi_website_faq","das_website_banners_faq",
                "das_main_page_banners1", "das_main_page_sections","das_splash_images","das_company_favicon_attachment","das_mobile_application",
                "das_branches_api","das_chef","das_client_api","das_drivers_api","das_uninstall_trigger",
                'das_user_login','das_user_secure','das_user_owner','das_company_translate_name','das_website_banner_footer_promotion',
                'das_company_informations_url','das_company_inherit','das_user_free_delivery','das_currency_inherit','das_add_is_default_address','das_add_to_card',
                'das_res_config_settings'],

    'installable': True,
    'sequence': -500,
    'application': True,
    'auto_install': False,
    "license": 'AGPL-3',
    "website": "https://das-360.com",

}
